spring:
  application:
    name: medimate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL} # ???? DB_URL? ??? jdbc:mysql://localhost:3306/medimate ??
    username: ${DB_USERNAME} # ???? DB_USERNAME? ??? root ??
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true